### ISSUE TITLE
Close to tray state doesn't persist between reboots

### ISSUE THREAD

**Issue by enx1998** [eneshecan/whatsapp-for-linux#65]
Hi,
I'm trying to use "Close To Tray" option, the icon correctly appear but when I click the window manager "x" button the application closes and the tray icon disappear.
When I launch whatsapp-for-linux from the cli I can see this messages:
```
Settings: Key file does not have key “close_to_tray” in group “General”
Segmentation error (core dump created)
```

Thanks ENx

**Comment by eneshecan** [comment]
Hi, thanks for reporting. Could you please tell me your distro and the package of the application you use?

**Comment by eneshecan** [comment]
It would be nice to hear how does this behave on different distros. It works properly on arch linux.

**Comment by enx1998** [comment]
Hi @eneshecan, I'm using Gentoo and I build it from sources.

**Comment by eran-pinhas** [comment]
I thnk the same happens in ubuntu, the window still shows, But the icon and menu are showing on the top bar

Cheers

**Comment by eneshecan** [comment]
Hi @eran-pinhas. Which Ubuntu distro are you on? Also, could you please elaborate more what you experience?

**Comment by eran-pinhas** [comment]
20.04. Really like the app, real simple to use, installed with snap. 

Thanks @eneshecan

**Comment by jyhelle** [comment]
Manjaro Linux, version 1.1.2-0, packaged the 6th of january : the close to tray option works, but the icon no longer shows in the tray, we have a blank space instead and clicking in it we have the normal open/quit menu (i.e., the icon doesn't show at all, even before first closing of the app, while it was working before that update)
Jan

**Comment by eneshecan** [comment]
@jyhelle Thanks for reporting! Tray icons are a bit problematic across distros :( Could you please debug the application and tell me what you get? This also applies to anyone having different problems. Any feedback would make us fix this faster.

**Comment by plop28** [comment]
Same problem on manjaro with kde plasma. The icon is in the taskbar when using the app, but disappears on close.

Settings: Key file does not have key “close_to_tray” in group “General”
Settings: Key file does not have key “header_bar” in group “General”

**Comment by bctorreira** [comment]
On Kubuntu, the "Close To Tray" option does not persist between reboots. That is, the option works as intended when enabled, but when I reboot the system and the program starts, the option is not enabled anymore.

**Comment by eneshecan** [comment]
Hi @bctorreira. If it doesn't save its state when the app is restarted, this might be related to a crash on exit causing to not being able to save settings. Could you please run the app from the terminal and report your observations?

**Comment by dt192** [comment]
I have the same issue on Manjaro/Gnome, of the setting working fine once turned on each session, but not persisting. 

```
** (whatsapp-for-linux:3695): WARNING **: 07:41:43.635: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory

Settings: Key file does not have key “allow_permissions” in group “Network”
Settings: Key file does not have key “close_to_tray” in group “General”
Settings: Key file does not have key “header_bar” in group “General”
```

**Comment by eneshecan** [comment]
Hi @dt192. Do you get a segfault when you exit the app?

**Comment by dt192** [comment]
> Hi @dt192. Do you get a segfault when you exit the app?

No, it gives no error message on exit.

**Comment by eneshecan** [comment]
> > Hi @dt192. Do you get a segfault when you exit the app?
> 
> No, it gives no error message on exit.

Thanks a lot for the information.

Interesting problem. Are you sure you are closing the application while close to tray is enabled? Otherwise, maybe the app isn't shut down properly when you restart the system while it's still running. Because I see from your log messages that closed_to_tray is not written to your settings configuration file.

**Comment by dt192** [comment]
> > > Hi @dt192. Do you get a segfault when you exit the app?
> > 
> > 
> > No, it gives no error message on exit.
> 
> Thanks a lot for the information.
> 
> Interesting problem. Are you sure you are closing the application while close to tray is enabled? Otherwise, maybe the app isn't shut down properly when you restart the system while it's still running. Because I see from your log messages that closed_to_tray is not written to your settings configuration file.

Hi, I just tested that and that does appear to be correct. If I set the setting, manually quit the app then restart the computer it persists, but If I restart the computer with the app still running it doesn't.

Is there a log somewhere I can check output from shutdown process?

**Comment by eneshecan** [comment]
> > > > Hi @dt192. Do you get a segfault when you exit the app?
> > > 
> > > 
> > > No, it gives no error message on exit.
> > 
> > Thanks a lot for the information.
> > 
> > Interesting problem. Are you sure you are closing the application while close to tray is enabled? Otherwise, maybe the app isn't shut down properly when you restart the system while it's still running. Because I see from your log messages that closed_to_tray is not written to your settings configuration file.
> 
> Hi, I just tested that and that does appear to be correct. If I set the setting, manually quit the app then restart the computer it persists, but If I restart the computer with the app still running it doesn't.
> 
> Is there a log somewhere I can check output from shutdown process?
> 
> I had a grep through the journal and the only other error related to the app I see here and there is `Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`

I believe the apps are killed as soon as xserver shuts down which causes them to crash. However, we might listen for sigkills and exit the app properly. Will try that soon.

**Comment by eneshecan** [comment]
I renamed the title to be precise. Others having different problems with the tray icon, please open another issue with a nice description. Also, have a great day!

**Comment by eneshecan** [comment]
Fixed with a13e4fee51f841a72e7788206d5a374940f8ca23

**Comment by enx1998** [comment]
Hi eneshecan,
you have closed this issue, but I still have the problem which led me to open this issue: the "Close To Tray" option doesn't work because when I close the window the app closes.
Thanks for your work,
ENx

**Comment by eneshecan** [comment]
Hi @enx1998. This will be available in the next release.
